import "./globals.css"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rehabit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="__className_73f86d">
      <body className={`antialiased`} >
        {children}
      </body>
    </html>
  );
}
